package com.aktic.indussahulatbackend.model.enums;

public enum NotificationType {
    EVENT_AMBULANCE_ASSIGN_REQUEST,
    EVENT_AMBULANCE_ASSIGN_ACCEPT,
    EVENT_AMBULANCE_ASSIGN_REJECT,
    EVENT_AMBULANCE_ASSIGN_EXPIRED,


    EVENT_HOSPITAL_ASSIGN_REQUEST,
    EVENT_HOSPITAL_ASSIGN_ACCEPT,
    EVENT_HOSPITAL_ASSIGN_REJECT,

}
