spring:
  application:
    name: Indus-sahulat-backend
  jackson:
    time-zone: UTC
  datasource:
    url: jdbc:postgresql://localhost:5432/IndusSahulat
    username: postgres
    password: 123456789
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 600000


server:
  port: 8080

logging:
  level:
    root: info
#    org:
#      springframework:
#        transaction:
#          interceptor: trace
#      hibernate:
#        SQL: debug
#        orm.jdbc:
#          binding: trace

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}

