spring:
  application:
    name: Indus-sahulat-backend
  jackson:
    time-zone: UTC
  datasource:
    #    url: jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres?user=postgres.uwmfmhuiarguikbxpweh&password=${SUPABASE_PASSWORD}
    url: jdbc:postgresql://localhost:5432/IndusSahulat
    username: postgres
    password: 123456789
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 600000


server:
  port: 8080

logging:
  level:
    root: info

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}

